// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrtugvutsvctdkmyrchh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydHVndnV0c3ZjdGRrbXlyY2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Mjg4MjUsImV4cCI6MjA1ODQwNDgyNX0.zHEaRLZh0tkyzXSUjbmcDgdHgf6tpL519j1HCqVlCbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);